// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    /* Only create the two persistent screens at boot — all others are
     * created on-demand via _ui_screen_change() lazy init callback.
     * This cuts boot time and saves ~50KB+ of RAM at startup. */
    ui_home_screen_init();
    ui_apps_menu_screen_init();

    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_home);
}

void ui_destroy(void)
{
    ui_home_screen_destroy();
    ui_apps_menu_screen_destroy();
    ui_clock_screen_destroy();
    ui_manual_screen_destroy();
    ui_sd_card_files_screen_destroy();
    ui_settings_screen_destroy();
    ui_wifi_screen_destroy();
    ui_update_screen_destroy();
    ui_usb_msc_screen_destroy();
    ui_tabview_screen_destroy();
    ui_message_box_screen_destroy();
    ui_date_picker_screen_destroy();
    ui_time_picker_screen_destroy();
    ui_t9_keyboard_screen_destroy();
}
