// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_CLOCK_H
#define UI_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clock
extern void ui_clock_screen_init(void);
extern void ui_clock_screen_destroy(void);
extern void ui_event_clock(lv_event_t * e);
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_clock_bg;
extern lv_obj_t * ui_up_;
extern lv_obj_t * ui_week_bg;
extern lv_obj_t * ui_week;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_time;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

