// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#include "../ui.h"

lv_obj_t * ui_home;
lv_obj_t * ui_home_bg;
lv_obj_t * ui_center;
lv_obj_t * ui_sd_on;
lv_obj_t * ui_sd_null;
lv_obj_t * ui_bat;
lv_obj_t * ui_mascot;
lv_obj_t * ui_soc;
lv_obj_t * ui_unit1;
lv_obj_t * ui_unit2;
lv_obj_t * ui_unit3;
lv_obj_t * ui_unit4;
lv_obj_t * ui_unit5;

/*
 * Home 十字导航布局：手势方向 = 动画方向（推送式）
 *
 *              [SD Files]  ← 上滑 MOVE_TOP / 摇杆 DOWN
 *                  |
 *  [Apps] ←— [HOME] —→ [Settings]
 *  右滑MOVE_RIGHT/摇杆LEFT   左滑MOVE_LEFT/摇杆RIGHT
 *                  ↓
 *             [Clock]  ← 下滑 MOVE_BOTTOM / 摇杆 UP
 *
 * 触摸手势：推送式 — 手指朝哪滑，画面朝哪移
 * 摇杆导航：见 launcher.cpp handlePhysicalNav()
 */
void ui_event_home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code != LV_EVENT_GESTURE) return;

    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    lv_indev_wait_release(lv_indev_get_act());

    switch (dir) {
        case LV_DIR_RIGHT:  /* 右滑 → Apps Menu */
            _ui_screen_change(&ui_apps_menu,     LV_SCR_LOAD_ANIM_MOVE_RIGHT,  300, 0, &ui_apps_menu_screen_init);
            break;
        case LV_DIR_LEFT:   /* 左滑 → Settings */
            _ui_screen_change(&ui_settings,      LV_SCR_LOAD_ANIM_MOVE_LEFT,   300, 0, &ui_settings_screen_init);
            break;
        case LV_DIR_TOP:    /* 上滑 → SD Card Files */
            _ui_screen_change(&ui_sd_card_files, LV_SCR_LOAD_ANIM_MOVE_TOP,    300, 0, &ui_sd_card_files_screen_init);
            break;
        case LV_DIR_BOTTOM: /* 下滑 → Clock */
            _ui_screen_change(&ui_clock,         LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0, &ui_clock_screen_init);
            break;
        default:
            break;
    }
}

// build funtions

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    /* Black canvas so semi-transparent edge pixels of the bg image blend dark, not white */
    lv_obj_set_style_bg_color(ui_home, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_bg = lv_img_create(ui_home);
    lv_img_set_src(ui_home_bg, &ui_img_background_h_png);
    lv_obj_set_width(ui_home_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_home_bg, LV_SIZE_CONTENT);    /// 241
    lv_obj_set_align(ui_home_bg, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(ui_home_bg, 0, 0);
    lv_obj_add_flag(ui_home_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_center = lv_img_create(ui_home);
    lv_img_set_src(ui_center, &ui_img_navigation_center_png);
    lv_obj_set_width(ui_center, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_center, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_center, 10);
    lv_obj_set_y(ui_center, 204);
    lv_obj_add_flag(ui_center, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_center, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /* SD 已插入图标（左上角 x=10,y=10，launcher updateStatusBar 控制可见性） */
    ui_sd_on = lv_img_create(ui_home);
    lv_img_set_src(ui_sd_on, &ui_img_storage_status_on_png);
    lv_obj_set_width(ui_sd_on, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_sd_on, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_sd_on, 10);
    lv_obj_set_y(ui_sd_on, 10);
    lv_obj_add_flag(ui_sd_on, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sd_on, LV_OBJ_FLAG_SCROLLABLE);

    /* SD 未插入图标（同位置，默认显示；热插拔后由 launcher 切换） */
    ui_sd_null = lv_img_create(ui_home);
    lv_img_set_src(ui_sd_null, &ui_img_storage_status_null_png);
    lv_obj_set_width(ui_sd_null, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_sd_null, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_sd_null, 10);
    lv_obj_set_y(ui_sd_null, 10);
    lv_obj_add_flag(ui_sd_null, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_sd_null, LV_OBJ_FLAG_SCROLLABLE);

    ui_bat = lv_img_create(ui_home);
    lv_img_set_src(ui_bat, &ui_img_power_gauge_png);
    lv_obj_set_width(ui_bat, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_bat, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_bat, 267);
    lv_obj_set_y(ui_bat, 10);
    lv_obj_add_flag(ui_bat, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mascot = lv_img_create(ui_home);
    lv_img_set_src(ui_mascot, &ui_img_mascot_png);
    lv_obj_set_width(ui_mascot, LV_SIZE_CONTENT);   /// 269
    lv_obj_set_height(ui_mascot, LV_SIZE_CONTENT);    /// 203
    lv_obj_set_x(ui_mascot, 26);
    lv_obj_set_y(ui_mascot, 17);
    lv_obj_add_flag(ui_mascot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mascot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_soc = lv_label_create(ui_home);
    lv_obj_set_width(ui_soc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soc, 210);
    lv_obj_set_y(ui_soc, 14);
    lv_label_set_text(ui_soc, "100/100");
    lv_obj_set_style_text_color(ui_soc, lv_color_hex(0xBDE600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soc, &ui_font_number_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unit1 = lv_img_create(ui_home);
    lv_img_set_src(ui_unit1, &ui_img_unit_png);
    lv_obj_set_width(ui_unit1, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_unit1, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_unit1, 276);
    lv_obj_set_y(ui_unit1, 15);
    lv_obj_add_flag(ui_unit1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_unit1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_unit2 = lv_img_create(ui_home);
    lv_img_set_src(ui_unit2, &ui_img_unit_png);
    lv_obj_set_width(ui_unit2, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_unit2, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_unit2, 282);
    lv_obj_set_y(ui_unit2, 15);
    lv_obj_add_flag(ui_unit2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_unit2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_unit3 = lv_img_create(ui_home);
    lv_img_set_src(ui_unit3, &ui_img_unit_png);
    lv_obj_set_width(ui_unit3, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_unit3, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_unit3, 288);
    lv_obj_set_y(ui_unit3, 15);
    lv_obj_add_flag(ui_unit3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_unit3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_unit4 = lv_img_create(ui_home);
    lv_img_set_src(ui_unit4, &ui_img_unit_png);
    lv_obj_set_width(ui_unit4, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_unit4, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_unit4, 294);
    lv_obj_set_y(ui_unit4, 15);
    lv_obj_add_flag(ui_unit4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_unit4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_unit5 = lv_img_create(ui_home);
    lv_img_set_src(ui_unit5, &ui_img_unit_png);
    lv_obj_set_width(ui_unit5, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_unit5, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_unit5, 300);
    lv_obj_set_y(ui_unit5, 15);
    lv_obj_add_flag(ui_unit5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_unit5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_home, ui_event_home, LV_EVENT_ALL, NULL);

}

void ui_home_screen_destroy(void)
{
    if(ui_home) lv_obj_del(ui_home);

    // NULL screen variables
    ui_home = NULL;
    ui_home_bg = NULL;
    ui_center = NULL;
    ui_sd_on = NULL;
    ui_sd_null = NULL;
    ui_bat = NULL;
    ui_mascot = NULL;
    ui_soc = NULL;
    ui_unit1 = NULL;
    ui_unit2 = NULL;
    ui_unit3 = NULL;
    ui_unit4 = NULL;
    ui_unit5 = NULL;

}
