// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern void ui_event_home(lv_event_t * e);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_home_bg;
extern lv_obj_t * ui_center;
extern lv_obj_t * ui_sd_on;
extern lv_obj_t * ui_sd_null;
extern lv_obj_t * ui_bat;
extern lv_obj_t * ui_mascot;
extern lv_obj_t * ui_soc;
extern lv_obj_t * ui_unit1;
extern lv_obj_t * ui_unit2;
extern lv_obj_t * ui_unit3;
extern lv_obj_t * ui_unit4;
extern lv_obj_t * ui_unit5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

