// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_MULTI_COLUMN_PICKER_H
#define UI_MULTI_COLUMN_PICKER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_multi_column_picker
extern void ui_multi_column_picker_screen_init(void);
extern void ui_multi_column_picker_screen_destroy(void);
extern lv_obj_t * ui_multi_column_picker;
extern lv_obj_t * ui_set_date_bg;
extern lv_obj_t * ui_set_date_header_bg;
extern lv_obj_t * ui_set_date_key_prompts_bg;
extern lv_obj_t * ui_set_date_key_a_bg;
extern lv_obj_t * ui_set_date_key_b_bg;
extern lv_obj_t * ui_set_date_header_label;
extern lv_obj_t * ui_set_date_key_a_save;
extern lv_obj_t * ui_set_date_key_b_back;
extern lv_obj_t * ui_picker_bg;
extern lv_obj_t * ui_Roller_month;
extern lv_obj_t * ui_Roller_day;
extern lv_obj_t * ui_Roller_year;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

