// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_MANUAL_H
#define UI_MANUAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_manual
extern void ui_manual_screen_init(void);
extern void ui_manual_screen_destroy(void);
extern lv_obj_t * ui_manual;
extern lv_obj_t * ui_date_time_bg;
extern lv_obj_t * ui_date_time_header_bg;
extern lv_obj_t * ui_date_time_key_prompts_bg;
extern lv_obj_t * ui_date_time_key_a_bg;
extern lv_obj_t * ui_date_time_key_b_bg;
extern lv_obj_t * ui_date_button;
extern lv_obj_t * ui_time_button;
extern lv_obj_t * ui_date_time_header_label;
extern lv_obj_t * ui_date_time_key_a_enter;
extern lv_obj_t * ui_date_time_key_b_back;
extern lv_obj_t * ui_manual_date;
extern lv_obj_t * ui_manual_time;

/* Focus management — called from launcher handlePhysicalNav() */
extern void ui_manual_set_focus(int idx);    /* 0=DATE, 1=TIME */
extern void ui_manual_enter_focused(void);   /* navigate into the focused picker */
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

