// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#include "../ui.h"

lv_obj_t * ui_message_box;
lv_obj_t * ui_message_box_windows;

// event funtions

// build funtions

void ui_message_box_screen_init(void)
{
    ui_message_box = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_message_box, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_message_box_windows = lv_img_create(ui_message_box);
    lv_img_set_src(ui_message_box_windows, &ui_img_message_box_bg_png);
    lv_obj_set_width(ui_message_box_windows, LV_SIZE_CONTENT);   /// 260
    lv_obj_set_height(ui_message_box_windows, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_align(ui_message_box_windows, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_message_box_windows, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_message_box_windows, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_message_box_screen_destroy(void)
{
    if(ui_message_box) lv_obj_del(ui_message_box);

    // NULL screen variables
    ui_message_box = NULL;
    ui_message_box_windows = NULL;

}
