// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#include "../ui.h"

lv_obj_t * ui_multi_column_picker;
lv_obj_t * ui_set_date_bg;
lv_obj_t * ui_set_date_header_bg;
lv_obj_t * ui_set_date_key_prompts_bg;
lv_obj_t * ui_set_date_key_a_bg;
lv_obj_t * ui_set_date_key_b_bg;
lv_obj_t * ui_set_date_header_label;
lv_obj_t * ui_set_date_key_a_save;
lv_obj_t * ui_set_date_key_b_back;
lv_obj_t * ui_picker_bg;
lv_obj_t * ui_Roller_month;
lv_obj_t * ui_Roller_day;
lv_obj_t * ui_Roller_year;

// event funtions

// build funtions

void ui_multi_column_picker_screen_init(void)
{
    ui_multi_column_picker = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_multi_column_picker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_set_date_bg = lv_img_create(ui_multi_column_picker);
    lv_img_set_src(ui_set_date_bg, &ui_img_background_v_png);
    lv_obj_set_width(ui_set_date_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_set_date_bg, LV_SIZE_CONTENT);    /// 241
    lv_obj_set_x(ui_set_date_bg, 0);
    lv_obj_set_y(ui_set_date_bg, -1);
    lv_obj_set_align(ui_set_date_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_set_date_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_set_date_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_set_date_header_bg = lv_img_create(ui_multi_column_picker);
    lv_img_set_src(ui_set_date_header_bg, &ui_img_header_png);
    lv_obj_set_width(ui_set_date_header_bg, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_set_date_header_bg, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_set_date_header_bg, 10);
    lv_obj_set_y(ui_set_date_header_bg, 3);
    lv_obj_add_flag(ui_set_date_header_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_set_date_header_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_set_date_key_prompts_bg = lv_img_create(ui_multi_column_picker);
    lv_img_set_src(ui_set_date_key_prompts_bg, &ui_img_key_prompts_bg_png);
    lv_obj_set_width(ui_set_date_key_prompts_bg, LV_SIZE_CONTENT);   /// 142
    lv_obj_set_height(ui_set_date_key_prompts_bg, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_set_date_key_prompts_bg, 168);
    lv_obj_set_y(ui_set_date_key_prompts_bg, 204);
    lv_obj_add_flag(ui_set_date_key_prompts_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_set_date_key_prompts_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_set_date_key_a_bg = lv_img_create(ui_multi_column_picker);
    lv_img_set_src(ui_set_date_key_a_bg, &ui_img_key_a_png);
    lv_obj_set_width(ui_set_date_key_a_bg, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_set_date_key_a_bg, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_set_date_key_a_bg, 171);
    lv_obj_set_y(ui_set_date_key_a_bg, 207);
    lv_obj_add_flag(ui_set_date_key_a_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_set_date_key_a_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_set_date_key_b_bg = lv_img_create(ui_multi_column_picker);
    lv_img_set_src(ui_set_date_key_b_bg, &ui_img_key_b_png);
    lv_obj_set_width(ui_set_date_key_b_bg, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_set_date_key_b_bg, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_set_date_key_b_bg, 241);
    lv_obj_set_y(ui_set_date_key_b_bg, 207);
    lv_obj_add_flag(ui_set_date_key_b_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_set_date_key_b_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_set_date_header_label = lv_label_create(ui_multi_column_picker);
    lv_obj_set_width(ui_set_date_header_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_set_date_header_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_set_date_header_label, 122);
    lv_obj_set_y(ui_set_date_header_label, 14);
    lv_label_set_text(ui_set_date_header_label, "Set Date");
    lv_obj_set_style_text_color(ui_set_date_header_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_set_date_header_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_set_date_header_label, &ui_font_name_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_set_date_key_a_save = lv_label_create(ui_multi_column_picker);
    lv_obj_set_width(ui_set_date_key_a_save, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_set_date_key_a_save, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_set_date_key_a_save, 195);
    lv_obj_set_y(ui_set_date_key_a_save, 210);
    lv_label_set_text(ui_set_date_key_a_save, "Save");
    lv_obj_set_style_text_color(ui_set_date_key_a_save, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_set_date_key_a_save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_set_date_key_a_save, &ui_font_name_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_set_date_key_b_back = lv_label_create(ui_multi_column_picker);
    lv_obj_set_width(ui_set_date_key_b_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_set_date_key_b_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_set_date_key_b_back, 267);
    lv_obj_set_y(ui_set_date_key_b_back, 210);
    lv_label_set_text(ui_set_date_key_b_back, "Back");
    lv_obj_set_style_text_color(ui_set_date_key_b_back, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_set_date_key_b_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_set_date_key_b_back, &ui_font_name_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_picker_bg = lv_img_create(ui_multi_column_picker);
    lv_img_set_src(ui_picker_bg, &ui_img_788348331);
    lv_obj_set_width(ui_picker_bg, LV_SIZE_CONTENT);   /// 301
    lv_obj_set_height(ui_picker_bg, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_picker_bg, 10);
    lv_obj_set_y(ui_picker_bg, 62);
    lv_obj_add_flag(ui_picker_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_picker_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller_month = lv_roller_create(ui_multi_column_picker);
    lv_roller_set_options(ui_Roller_month, "JAN\nFEB\nMAR\nAPR\nMAY\nJUN\nJUL\nAUG\nSEP\nOCT\nNOV\nDEC",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller_month, 120);
    lv_obj_set_width(ui_Roller_month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller_month, -100);
    lv_obj_set_y(ui_Roller_month, 6);
    lv_obj_set_align(ui_Roller_month, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller_month, lv_color_hex(0xBDE600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_month, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller_month, &ui_font_name_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_month, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_month, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller_month, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller_month, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller_month, lv_color_hex(0xBDE600), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_month, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_month, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_month, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Roller_day = lv_roller_create(ui_multi_column_picker);
    lv_roller_set_options(ui_Roller_day,
                          "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller_day, 120);
    lv_obj_set_width(ui_Roller_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller_day, 0);
    lv_obj_set_y(ui_Roller_day, 6);
    lv_obj_set_align(ui_Roller_day, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller_day, lv_color_hex(0xBDE600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_day, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller_day, &ui_font_name_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_day, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_day, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller_day, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller_day, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller_day, lv_color_hex(0xBDE600), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_day, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_day, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_day, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Roller_year = lv_roller_create(ui_multi_column_picker);
    lv_roller_set_options(ui_Roller_year, "2024\n2025\n2026\n2027\n2028\n2029\n2030\n2031\n2032\n2033\n2034\n2035",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Roller_year, 1, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller_year, 120);
    lv_obj_set_width(ui_Roller_year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller_year, 100);
    lv_obj_set_y(ui_Roller_year, 6);
    lv_obj_set_align(ui_Roller_year, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller_year, lv_color_hex(0xBDE600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_year, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller_year, &ui_font_name_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_year, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_year, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller_year, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller_year, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller_year, lv_color_hex(0xBDE600), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_year, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_year, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_year, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

}

void ui_multi_column_picker_screen_destroy(void)
{
    if(ui_multi_column_picker) lv_obj_del(ui_multi_column_picker);

    // NULL screen variables
    ui_multi_column_picker = NULL;
    ui_set_date_bg = NULL;
    ui_set_date_header_bg = NULL;
    ui_set_date_key_prompts_bg = NULL;
    ui_set_date_key_a_bg = NULL;
    ui_set_date_key_b_bg = NULL;
    ui_set_date_header_label = NULL;
    ui_set_date_key_a_save = NULL;
    ui_set_date_key_b_back = NULL;
    ui_picker_bg = NULL;
    ui_Roller_month = NULL;
    ui_Roller_day = NULL;
    ui_Roller_year = NULL;

}
