// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_MESSAGE_BOX_H
#define UI_MESSAGE_BOX_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_message_box
extern void ui_message_box_screen_init(void);
extern void ui_message_box_screen_destroy(void);
extern lv_obj_t * ui_message_box;
extern lv_obj_t * ui_message_box_windows;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

