// This file was generated by SquareLine Studio, then extended to support
// SD card file browsing via ui_sd_bridge (no launcher involvement).
//
// Navigation model:
//   Tap a folder       → enter that folder (_item_click_cb)
//   Tap B icon / phys B → back one level  (ui_sd_card_files_action_back)
//   Physical A         → return to Home   (handled by launcher handlePhysicalNav)
//   Joystick up        → return to Home   (handled by launcher handlePhysicalNav)
//   Bottom swipe       → return to Home   (ui_event_sd_card_files gesture)
//
// LVGL version: 8.3.11

#include "../ui.h"
#include "../ui_sd_bridge.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

/* ── Widget declarations ─────────────────────────────────────────── */
lv_obj_t * ui_sd_card_files;
lv_obj_t * ui_sd_card_files_bg;
lv_obj_t * ui_down;
lv_obj_t * ui_sd_header_bg;
lv_obj_t * ui_list_border;
lv_obj_t * ui_key_prompts_bg;
lv_obj_t * ui_key_a_bg;
lv_obj_t * ui_key_b_bg;
lv_obj_t * ui_sd_header_label;
lv_obj_t * ui_key_a_enter;
lv_obj_t * ui_key_b_back;

/* ── State ───────────────────────────────────────────────────────── */
#define SD_PATH_MAX 256

static char       _current_path[SD_PATH_MAX] = "/";
static lv_obj_t * _file_list                 = NULL;

typedef struct {
    char    path[SD_PATH_MAX];
    uint8_t is_dir;
} sd_item_t;

/* ── Forward declaration ─────────────────────────────────────────── */
static void _build_file_list(void);

/* ── Path helpers ────────────────────────────────────────────────── */

/* Returns 1 if moved up, 0 if already at root. */
static int _path_pop(void)
{
    if (strcmp(_current_path, "/") == 0) return 0;
    char * slash = strrchr(_current_path, '/');
    if (!slash) { strcpy(_current_path, "/"); return 1; }
    if (slash == _current_path)
        _current_path[1] = '\0';   /* keep leading "/" */
    else
        *slash = '\0';
    return 1;
}

/* ── Item lifecycle callbacks ────────────────────────────────────── */

static void _item_click_cb(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    sd_item_t * it = (sd_item_t *)lv_event_get_user_data(e);
    if (!it || !it->is_dir) return;
    strncpy(_current_path, it->path, sizeof(_current_path) - 1);
    _current_path[sizeof(_current_path) - 1] = '\0';
    _build_file_list();
}

static void _item_delete_cb(lv_event_t * e)
{
    sd_item_t * it = (sd_item_t *)lv_event_get_user_data(e);
    if (it) free(it);
}

/* ── Per-entry visitor (called once per dir entry by ui_sd_list_dir) */
typedef struct { int row; } _visit_ctx_t;

static void _visit_entry(const char * name, int is_dir, void * user)
{
    _visit_ctx_t * ctx = (_visit_ctx_t *)user;
    if (!_file_list || !name) return;

    /* Shorten known long system folder names for display */
    const char * display_name = name;
    if (strcasecmp(name, "System Volume Information") == 0) display_name = "system";

    sd_item_t * it = (sd_item_t *)malloc(sizeof(sd_item_t));
    if (!it) return;
    it->is_dir = (uint8_t)(is_dir != 0);
    if (strcmp(_current_path, "/") == 0)
        snprintf(it->path, sizeof(it->path), "/%s", name);
    else
        snprintf(it->path, sizeof(it->path), "%s/%s", _current_path, name);

    /* 3 rows visible in 142px container: height=44, stride=46 */
    lv_obj_t * btn = lv_btn_create(_file_list);
    lv_obj_set_width(btn, 280);
    lv_obj_set_height(btn, 44);
    lv_obj_set_x(btn, 0);
    lv_obj_set_y(btn, (lv_coord_t)(ctx->row * 46));
    lv_obj_set_style_bg_opa(btn,   LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(btn, lv_color_hex(0xBBE700), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(btn,   80,            LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_radius(btn,   4, 0);
    lv_obj_set_style_border_width(btn, 0, 0);
    lv_obj_set_style_shadow_opa(btn, LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_all(btn,  0, 0);
    lv_obj_clear_flag(btn, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t * icon = lv_label_create(btn);
    lv_label_set_text(icon, is_dir ? LV_SYMBOL_DIRECTORY : LV_SYMBOL_FILE);
    lv_obj_set_style_text_font(icon, LV_FONT_DEFAULT, 0);
    lv_obj_set_style_text_color(icon, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_align(icon, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(icon, 6);

    lv_obj_t * lbl = lv_label_create(btn);
    lv_label_set_text(lbl, display_name);
    lv_obj_set_style_text_color(lbl, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_text_font(lbl, &ui_font_name_14, 0);
    lv_obj_set_align(lbl, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(lbl, 24);

    lv_obj_add_event_cb(btn, _item_click_cb,  LV_EVENT_CLICKED, it);
    lv_obj_add_event_cb(btn, _item_delete_cb, LV_EVENT_DELETE,  it);
    ctx->row++;
}

/* ── Build (or rebuild) the visible list ────────────────────────── */

static void _build_file_list(void)
{
    if (!_file_list) return;
    lv_obj_clean(_file_list);  /* LV_EVENT_DELETE → frees each sd_item_t */

    if (ui_sd_header_label) {
        if (strcmp(_current_path, "/") == 0)
            lv_label_set_text(ui_sd_header_label, "SD Card Files");
        else
            lv_label_set_text_fmt(ui_sd_header_label, "SD%s", _current_path);
    }

    _visit_ctx_t ctx = { 0 };
    int rc = ui_sd_list_dir(_current_path, _visit_entry, &ctx);

    if (rc != 0 || ctx.row == 0) {
        lv_obj_t * lbl = lv_label_create(_file_list);
        lv_label_set_text(lbl, rc != 0 ? "(No SD card)" : "(Empty)");
        lv_obj_set_style_text_color(lbl, lv_color_hex(0xFFFFFF), 0);
        lv_obj_set_style_text_font(lbl,  &ui_font_name_14, 0);
        lv_obj_set_pos(lbl, 60, 50);
    }
}

/* ── Public: pop one folder level ────────────────────────────────── */

void ui_sd_card_files_action_back(void)
{
    if (_path_pop()) {
        _build_file_list();
    } else {
        /* Already at root — exit to home */
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_home_screen_init);
    }
}

static void _on_key_b_click(lv_event_t * e)
{
    (void)e;
    ui_sd_card_files_action_back();
}

/* ── Screen-level event (bottom swipe → home) ───────────────────── */

void ui_event_sd_card_files(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_GESTURE &&
        lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_home_screen_init);
    }
}

/* ── Screen init ─────────────────────────────────────────────────── */

void ui_sd_card_files_screen_init(void)
{
    strcpy(_current_path, "/");

    ui_sd_card_files = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sd_card_files, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sd_card_files_bg = lv_img_create(ui_sd_card_files);
    lv_img_set_src(ui_sd_card_files_bg, &ui_img_background_v_png);
    lv_obj_set_width(ui_sd_card_files_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_sd_card_files_bg, LV_SIZE_CONTENT);    /// 241
    lv_obj_set_x(ui_sd_card_files_bg, 0);
    lv_obj_set_y(ui_sd_card_files_bg, -1);
    lv_obj_set_align(ui_sd_card_files_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sd_card_files_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sd_card_files_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_down = lv_img_create(ui_sd_card_files);
    lv_img_set_src(ui_down, &ui_img_navigation_edge_png);
    lv_obj_set_width(ui_down, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_down, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_down, 10);
    lv_obj_set_y(ui_down, 204);
    lv_obj_add_flag(ui_down, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_down, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_down, -1800);

    ui_sd_header_bg = lv_img_create(ui_sd_card_files);
    lv_img_set_src(ui_sd_header_bg, &ui_img_header_png);
    lv_obj_set_width(ui_sd_header_bg, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_sd_header_bg, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_sd_header_bg, 10);
    lv_obj_set_y(ui_sd_header_bg, 3);
    lv_obj_add_flag(ui_sd_header_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sd_header_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_list_border = lv_img_create(ui_sd_card_files);
    lv_img_set_src(ui_list_border, &ui_img_border_png);
    lv_obj_set_width(ui_list_border, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_list_border, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_list_border, 10);
    lv_obj_set_y(ui_list_border, 47);
    lv_obj_add_flag(ui_list_border, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_list_border, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /* Scrollable file list — transparent, 5 px inset inside ui_list_border */
    _file_list = lv_obj_create(ui_sd_card_files);
    lv_obj_set_x(_file_list, 15);
    lv_obj_set_y(_file_list, 52);
    lv_obj_set_size(_file_list, 290, 142);
    lv_obj_set_style_bg_opa(_file_list,     LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(_file_list, 0, 0);
    lv_obj_set_style_pad_all(_file_list,    0, 0);
    lv_obj_set_style_radius(_file_list,     0, 0);
    lv_obj_set_scroll_dir(_file_list, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(_file_list, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_style_bg_color(_file_list, lv_color_hex(0xBBE700),
                               LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(_file_list, 255,
                             LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_key_prompts_bg = lv_img_create(ui_sd_card_files);
    lv_img_set_src(ui_key_prompts_bg, &ui_img_key_prompts_bg_png);
    lv_obj_set_width(ui_key_prompts_bg, LV_SIZE_CONTENT);   /// 142
    lv_obj_set_height(ui_key_prompts_bg, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_key_prompts_bg, 168);
    lv_obj_set_y(ui_key_prompts_bg, 204);
    lv_obj_add_flag(ui_key_prompts_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_key_prompts_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /* A key — NOT clickable; physical A → Home via launcher handlePhysicalNav */
    ui_key_a_bg = lv_img_create(ui_sd_card_files);
    lv_img_set_src(ui_key_a_bg, &ui_img_key_a_png);
    lv_obj_set_width(ui_key_a_bg, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_key_a_bg, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_key_a_bg, 171);
    lv_obj_set_y(ui_key_a_bg, 207);
    lv_obj_add_flag(ui_key_a_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_key_a_bg, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);

    /* B key — clickable; tap or physical B → back one level */
    ui_key_b_bg = lv_img_create(ui_sd_card_files);
    lv_img_set_src(ui_key_b_bg, &ui_img_key_b_png);
    lv_obj_set_width(ui_key_b_bg, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_key_b_bg, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_key_b_bg, 241);
    lv_obj_set_y(ui_key_b_bg, 207);
    lv_obj_add_flag(ui_key_b_bg, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_key_b_bg, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(ui_key_b_bg, _on_key_b_click, LV_EVENT_CLICKED, NULL);

    ui_sd_header_label = lv_label_create(ui_sd_card_files);
    lv_obj_set_width(ui_sd_header_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sd_header_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sd_header_label, 97);
    lv_obj_set_y(ui_sd_header_label, 14);
    lv_label_set_text(ui_sd_header_label, "SD Card Files");
    lv_obj_set_style_text_color(ui_sd_header_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sd_header_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sd_header_label, &ui_font_name_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_key_a_enter = lv_label_create(ui_sd_card_files);
    lv_obj_set_width(ui_key_a_enter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_key_a_enter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_key_a_enter, 195);
    lv_obj_set_y(ui_key_a_enter, 210);
    lv_label_set_text(ui_key_a_enter, "Enter");
    lv_obj_set_style_text_color(ui_key_a_enter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_key_a_enter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_key_a_enter, &ui_font_name_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_key_b_back = lv_label_create(ui_sd_card_files);
    lv_obj_set_width(ui_key_b_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_key_b_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_key_b_back, 267);
    lv_obj_set_y(ui_key_b_back, 210);
    lv_label_set_text(ui_key_b_back, "Back");
    lv_obj_set_style_text_color(ui_key_b_back, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_key_b_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_key_b_back, &ui_font_name_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    _build_file_list();

    lv_obj_add_event_cb(ui_sd_card_files, ui_event_sd_card_files, LV_EVENT_ALL, NULL);
}

/* ── Screen destroy ──────────────────────────────────────────────── */

void ui_sd_card_files_screen_destroy(void)
{
    if (ui_sd_card_files) lv_obj_del(ui_sd_card_files);
    /* lv_obj_del fires LV_EVENT_DELETE on all descendants → frees sd_item_t */

    ui_sd_card_files    = NULL;
    ui_sd_card_files_bg = NULL;
    ui_down             = NULL;
    ui_sd_header_bg     = NULL;
    ui_list_border      = NULL;
    ui_key_prompts_bg   = NULL;
    ui_key_a_bg         = NULL;
    ui_key_b_bg         = NULL;
    ui_sd_header_label  = NULL;
    ui_key_a_enter      = NULL;
    ui_key_b_back       = NULL;
    _file_list          = NULL;
    strcpy(_current_path, "/");
}
