// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_SD_CARD_FILES_H
#define UI_SD_CARD_FILES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sd_card_files
extern void ui_sd_card_files_screen_init(void);
extern void ui_sd_card_files_screen_destroy(void);
extern void ui_event_sd_card_files(lv_event_t * e);
extern void ui_sd_card_files_action_back(void);
extern lv_obj_t * ui_sd_card_files;
extern lv_obj_t * ui_sd_card_files_bg;
extern lv_obj_t * ui_down;
extern lv_obj_t * ui_sd_header_bg;
extern lv_obj_t * ui_list_border;
extern lv_obj_t * ui_key_prompts_bg;
extern lv_obj_t * ui_key_a_bg;
extern lv_obj_t * ui_key_b_bg;
extern lv_obj_t * ui_sd_header_label;
extern lv_obj_t * ui_key_a_enter;
extern lv_obj_t * ui_key_b_back;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

