// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings
extern void ui_settings_screen_init(void);
extern void ui_settings_screen_destroy(void);
extern void ui_event_settings(lv_event_t * e);
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_settings_bg;
extern lv_obj_t * ui_brightness_bar_bg;
extern lv_obj_t * ui_volume_bar_bg;
extern lv_obj_t * ui_wifi_status;
extern lv_obj_t * ui_settings_button_bg;
extern lv_obj_t * ui_settings_button;
extern lv_obj_t * ui_ble_button;
extern lv_obj_t * ui_msc_button;
extern lv_obj_t * ui_info_button;
extern lv_obj_t * ui_bar_brightness_icon;
extern lv_obj_t * ui_bar_volume_icon;
extern lv_obj_t * ui_brightness_slider;
extern lv_obj_t * ui_volume_slider;
extern lv_obj_t * ui_navigation_right;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

