// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_TABVIEW_H
#define UI_TABVIEW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tabview
extern void ui_tabview_screen_init(void);
extern void ui_tabview_screen_destroy(void);
extern lv_obj_t * ui_tabview;
extern lv_obj_t * ui_tabview_settings;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_TabPage5;
extern lv_obj_t * ui_tab_key_prompts_bg;
extern lv_obj_t * ui_tab_key_a_bg;
extern lv_obj_t * ui_tab_key_b_bg;
extern lv_obj_t * ui_tab_key_a_save;
extern lv_obj_t * ui_tab_key_a_back;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

