// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#include "../ui.h"

lv_obj_t * ui_update;
lv_obj_t * ui_update_bg;
lv_obj_t * ui_mascot_update;
lv_obj_t * ui_updateing;
lv_obj_t * ui_update_progress;

// event funtions

// build funtions

void ui_update_screen_init(void)
{
    ui_update = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_update, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_update, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_update, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_update_bg = lv_img_create(ui_update);
    lv_img_set_src(ui_update_bg, &ui_img_background_png);
    lv_obj_set_width(ui_update_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_update_bg, LV_SIZE_CONTENT);    /// 241
    lv_obj_set_align(ui_update_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_update_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_update_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mascot_update = lv_img_create(ui_update);
    lv_img_set_src(ui_mascot_update, &ui_img_mascot_update_png);
    lv_obj_set_width(ui_mascot_update, LV_SIZE_CONTENT);   /// 292
    lv_obj_set_height(ui_mascot_update, LV_SIZE_CONTENT);    /// 196
    lv_obj_set_align(ui_mascot_update, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mascot_update, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mascot_update, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_updateing = lv_label_create(ui_update);
    lv_obj_set_width(ui_updateing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_updateing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_updateing, 20);
    lv_obj_set_y(ui_updateing, 18);
    lv_label_set_text(ui_updateing, "Updateing");
    lv_obj_set_style_text_color(ui_updateing, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_updateing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_updateing, &ui_font_name_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_update_progress = lv_label_create(ui_update);
    lv_obj_set_width(ui_update_progress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_update_progress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_update_progress, 175);
    lv_obj_set_y(ui_update_progress, 173);
    lv_label_set_text(ui_update_progress, "100%");
    lv_obj_set_style_text_color(ui_update_progress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_update_progress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_update_progress, &ui_font_name_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_update_screen_destroy(void)
{
    if(ui_update) lv_obj_del(ui_update);

    // NULL screen variables
    ui_update = NULL;
    ui_update_bg = NULL;
    ui_mascot_update = NULL;
    ui_updateing = NULL;
    ui_update_progress = NULL;

}
