// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_UPDATE_H
#define UI_UPDATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_update
extern void ui_update_screen_init(void);
extern void ui_update_screen_destroy(void);
extern lv_obj_t * ui_update;
extern lv_obj_t * ui_update_bg;
extern lv_obj_t * ui_mascot_update;
extern lv_obj_t * ui_updateing;
extern lv_obj_t * ui_update_progress;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

