// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_USB_MSC_H
#define UI_USB_MSC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_usb_msc
extern void ui_usb_msc_screen_init(void);
extern void ui_usb_msc_screen_destroy(void);
extern lv_obj_t * ui_usb_msc;
extern lv_obj_t * ui_usb_msc_bg;
extern lv_obj_t * ui_mascot_usb_msc;
extern lv_obj_t * ui_usb_msc_label;
extern lv_obj_t * ui_usb_msc_key_prompts_bg;
extern lv_obj_t * ui_usb_msc_key_a_bg;
extern lv_obj_t * ui_usb_msc_key_b_bg;
extern lv_obj_t * ui_usb_msc_key_a_eject;
extern lv_obj_t * ui_usb_msc_key_b_back;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

