// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef UI_WIFI_H
#define UI_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifi
extern void ui_wifi_screen_init(void);
extern void ui_wifi_screen_destroy(void);
extern void ui_event_wifi(lv_event_t * e);
/** Connect the last-tapped row (used by physical A button in launcher). */
extern void ui_wifi_connect_focused(void);
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_wifi_bg;
extern lv_obj_t * ui_wifi_header_bg;
extern lv_obj_t * ui_wifi_list_border;
extern lv_obj_t * ui_wifi_key_prompts_bg;
extern lv_obj_t * ui_wifi_key_a_bg;
extern lv_obj_t * ui_wifi_key_b_bg;
extern lv_obj_t * ui_wifi_header_label;
extern lv_obj_t * ui_wifi_key_a_home;
extern lv_obj_t * ui_wifi_key_b_back;
extern lv_obj_t * ui_wifi_scan_switch;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif